### ISSUE TITLE
Etc.getlogin won't always return the current user

### ISSUE THREAD

**Issue by garnieretienne** [journeyapps/foreman_god#1]
`Etc.getlogin` will return the logged in user. If I log in using `user1` and later do `sudo su - user2`, `Etc.getlogin` will return `user1`.

When starting god with `user2`, it will try to set the uid and gid to `user2` because `Etc.getlogin` will return `user1`.

The problem is god can't set uid or gid if the current user is not `root`.

I propose to use `Etc.getpwuid(Process.uid).name` instead.

See: http://compgroups.net/comp.lang.ruby/env-class-bug/743056

**Comment by HerbCSO** [comment]
Sorry to comment on an old issue, but I am intensely curious as to why the call to `Process.uid` is in here because it seems to me that `Etc.getpwuid.name` would be equivalent. I also asked [an SO question](http://stackoverflow.com/questions/42391177/why-would-i-need-to-specify-uid-in-a-call-to-etc-getpwuid-if-im-trying-to-get-t) about that which has more detail - would love it if you could explain the reasoning there.

Thanks in advance!

**Comment by rkistner** [comment]
@HerbCSO Haven't confirmed it, but they do seem equivalent. From the source it seems like `Etc.getpwuid` defaults to using `getuid()`, which is the same as what `Process.uid` returns. So there shouldn't be any functional difference, but this version is a little more explicit in what is used.

**Comment by HerbCSO** [comment]
Thanks for the quick reply @rkistner. Take a look at my SO question, in there I tender a mild suspicion that it _may_ have something to do with Windows compatibility (although since `god` doesn't work on Windows, this would only be relevant if this was cargo-culted from the solution referenced in http://compgroups.net/comp.lang.ruby/env-class-bug/743056, but this all seems rather tenuous...). So your answer about it just making it explicit probably makes more sense.
