### ISSUE TITLE
Specify alternative log directory

### ISSUE THREAD

**Issue by snicker** [journeyapps/foreman_god#7]
I may have missed this, but is there somewhere that I can specify where the logs for the application go?

**Comment by rkistner** [comment]
You can specify the log path in the `.foreman` file with the `log` key, see [samples/configuration/.foreman](https://github.com/embarkmobile/foreman_god/blob/master/samples/configuration/.foreman) for an example. The log path can be absolute or relative path to a folder. Each instance of each app gets a separate log file in this folder.

If you need to log to a specific file, I recommend you do the logging from the app itself, instead of logging to stdout.
